agent_name: testagent
author: ducky
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.65.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections: 
- valory/abci:0.1.0
- valory/p2p_libp2p_client:0.1.0
contracts: []
protocols:
- open_aea/signing:1.0.0:bafybeig2d36zxy65vd7fwhs7scotuktydcarm74aprmrb5nioiymr3yixm
- valory/abci:0.1.0
- fetchai/default:1.0.0
skills:
- ducky/testbehaviourskill:0.1.0:bafybeibmpsaob2a7ugkut7dhnd2jmkfuebtd2jibcwkmrzjp4mt32bjd7a
- valory/abstract_abci:0.1.0
- valory/abstract_round_abci:0.1.0
customs: []
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: your_name/test_skill:0.1.0
  host: ${str:localhost}
  port: ${int:26659}
